# Generated by Django 3.2.8 on 2021-10-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ['ranking']},
        ),
        migrations.AlterModelOptions(
            name='blogentry',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='ranking',
            field=models.IntegerField(default=1),
        ),
    ]
