# Generated by Django 3.2.8 on 2021-10-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211016_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='cv_cateogry',
            field=models.BooleanField(default=False),
        ),
    ]
