# Generated by Django 3.2.8 on 2021-10-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_cv_cateogry_blogcategory_cv_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='blog',
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='blog',
            field=models.ManyToManyField(to='blog.BlogEntry'),
        ),
    ]
