# Generated by Django 3.2.8 on 2021-10-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
