# Generated by Django 3.2.8 on 2021-10-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogcategory_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='draft',
        ),
        migrations.AddField(
            model_name='blogentry',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
