# Generated by Django 3.2.8 on 2021-10-25 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20211025_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogimage',
            options={'ordering': ['title']},
        ),
    ]
