name: CI

on:
  pull_request

env:
  NODE_VERSION: 16
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: test-db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test-db

    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: migrate db
        run: npx prisma db push

      - name: Build
        run: npm run ci:build

      - name: Test
        run: npm run test:remote
