# Generated by Django 3.2.8 on 2021-10-13 10:33

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='interests',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cv_interests', to='cv.listitem'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='languages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cs_languages', to='cv.listitem'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='personality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cv_personality', to='cv.listitem'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='skills_levels',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cv_skills_levels', to='cv.skillslevel'),
        ),
        migrations.AlterField(
            model_name='eventitem',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventitem',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='icon_html',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
