# Generated by Django 3.2.8 on 2021-10-13 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20211013_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='personality',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='skills_levels',
        ),
        migrations.AddField(
            model_name='skillslevel',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.cv'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('listitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cv.listitem')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.cv')),
            ],
            bases=('cv.listitem',),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('listitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cv.listitem')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.cv')),
            ],
            bases=('cv.listitem',),
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('listitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cv.listitem')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.cv')),
            ],
            bases=('cv.listitem',),
        ),
    ]
