# Generated by Django 3.2.8 on 2021-10-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20211013_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='ranking',
            field=models.IntegerField(default=1),
        ),
    ]
