# Generated by Django 3.2.8 on 2021-10-13 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_listitem_ranking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listitem',
            options={'ordering': ['ranking', 'title']},
        ),
    ]
