# Generated by Django 3.2.8 on 2021-10-13 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_alter_listitem_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillslevel',
            name='skills',
        ),
        migrations.AddField(
            model_name='listitem',
            name='skill_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cv.skillslevel'),
        ),
    ]
