# Generated by Django 3.2.8 on 2021-10-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_auto_20211013_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillslevel',
            options={'ordering': ['ranking']},
        ),
        migrations.AddField(
            model_name='skillslevel',
            name='ranking',
            field=models.IntegerField(default=1),
        ),
    ]
