# Generated by Django 3.2.8 on 2021-10-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_auto_20211013_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='github_display_text',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cv',
            name='linked_in_display_text',
            field=models.CharField(default='', max_length=255),
        ),
    ]
