# Generated by Django 3.2.8 on 2021-10-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_auto_20211015_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='profile_picture',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
