# Generated by Django 3.2.8 on 2021-10-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0009_cv_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='phone_number_no_spaces',
            field=models.CharField(default='', max_length=25),
        ),
    ]
