# Generated by Django 3.2.8 on 2021-10-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0011_alter_listitem_skill_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventitem',
            name='subtitle',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
