# Generated by Django 3.2.8 on 2021-10-15 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0012_alter_eventitem_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventitem',
            name='cv',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cv.cv'),
        ),
    ]
